server:
  port: 8080
  servlet:
    context-path: /api

# Datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tm_dev?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qwer!234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
